import { useState } from 'react'
import { ArrowDownToLine, ArrowRight, BookOpen, Check, ChevronRight, CircleHelp, Clock3, Code2, Database, FileSearch, Filter, FlaskConical, GitBranch, Link2, ListChecks, Play, Search, ShieldCheck, Sparkles } from 'lucide-react'
import type { Annotation, Comparison, Report, Run, Work } from '../types'
import { checkEvidence, formatPercent, groups, productScopeNote, scopeNames, valueNames } from './domain'
import { TracePanel } from './panels'

export function LibraryPanel({ works, local, openWork, openImport, runs, openRun }: { works: Work[]; local: boolean; openWork: (w: Work) => void; openImport: () => void; runs: Run[]; openRun: (r: Run) => void }) {
  const [search, setSearch] = useState('')
  const [scope, setScope] = useState('all')
  const filtered = works.filter(w => `${w.title} ${w.id} ${w.author}`.toLowerCase().includes(search.toLowerCase()) && (scope === 'all' || w.scope === scope))
  const reviewed = works.flatMap(w => w.annotations).filter(a => a.reviewStatus === '已审核' && a.value !== 'unknown').length
  const evCount = works.reduce((n, w) => n + w.evidence.filter(e => checkEvidence(w, e)).length, 0)
  return <>
    <section className="intro-grid">
      <div className="research-intro"><div className="eyebrow light">A SMALLER QUESTION. A CLEARER ANSWER.</div><h2>读懂情绪承诺，<br />也看清证据边界。</h2><p>{productScopeNote}<br className="desktop-br" />每个内容判断都回到原文，每条建议都有验证路径。</p><div className="intro-flow"><span>内容理解</span><ArrowRight size={13} /><span>证据审核</span><ArrowRight size={13} /><span>策略验证</span></div><div className="orb orb-one" /><div className="orb orb-two" /></div>
      <div className="stat-grid"><div className="stat"><BookOpen size={18} /><strong>{works.length.toString().padStart(2, '0')}</strong><span>当前作品</span><small>{works.filter(w => w.scope === 'full_text').length} 篇全文 · 其余保留范围限制</small></div><div className="stat"><Link2 size={18} /><strong>{evCount.toString().padStart(2, '0')}</strong><span>精确原文引用</span><small>Unicode 位置与版本校验</small></div><div className="stat"><ShieldCheck size={18} /><strong>{reviewed.toString().padStart(2, '0')}</strong><span>已审核非空判断</span><small>{works.every(w => w.isSynthetic) ? '预计算演示状态，非人工金标' : '仍需复查语义是否成立'}</small></div><div className="stat"><Database size={18} /><strong>{works.filter(w => w.observations?.length).length.toString().padStart(2, '0')}</strong><span>包含指标的作品</span><small>不表示指标已通过可比性检查</small></div></div>
    </section>
    <section className="card library-card"><div className="section-heading"><div><h2>研究样本 <span className="count">{works.length}</span></h2><p>来源、文本范围和审核进度，一眼可见。</p></div><span className="caption">{local ? '存储于本地 SQLite' : '预计算快照 / 只读'}</span></div><div className="toolbar"><label className="search-input"><Search size={16} /><input aria-label="搜索作品" placeholder="搜索作品名称、作者或编号" value={search} onChange={e => setSearch(e.target.value)} />{search && <button onClick={() => setSearch('')} aria-label="清除搜索">×</button>}</label><label className="filter-select"><Filter size={14} /><select aria-label="筛选文本范围" value={scope} onChange={e => setScope(e.target.value)}><option value="all">全部文本范围</option>{Object.entries(scopeNames).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label></div>
      <div className="table-scroll"><table className="works-table"><thead><tr><th>作品 / 来源</th><th>文本范围</th><th>内容判断</th><th>指标完整性</th><th>审核状态</th><th><span className="sr-only">操作</span></th></tr></thead><tbody>{filtered.map((w, i) => <tr key={w.id}><td><button className="work-link" onClick={() => openWork(w)}><span className={`book-tile book-${i % 4}`}><BookOpen size={19} /></span><span><b>{w.title}</b><small>{w.id} · {w.isSynthetic ? '原创演示' : w.sourceType}</small></span></button></td><td><span className={`pill ${w.scope === 'full_text' ? 'green' : 'neutral'}`}>{scopeNames[w.scope]}</span><small className="cell-sub">{w.versionId} · {w.paragraphs.length} 个段落</small></td><td><b>{w.annotations.filter(a => a.value !== 'unknown').length}</b><span className="muted"> / {groups.length} 类</span><small className="cell-sub">{w.evidence.length} 条候选引用</small></td><td><span className={`status-text ${w.observations?.length ? 'teal' : 'muted'}`}><i />{w.observations?.length ? '有记录 · 待口径检查' : '无指标 · 不参与 CTR'}</span></td><td><span className={`pill ${w.reviewStatus === '已审核' ? 'green' : w.reviewStatus === '需复核' ? 'amber' : 'neutral'}`}>{w.reviewStatus}</span></td><td><button className="icon-btn row-open" aria-label={`查看${w.title}`} onClick={() => openWork(w)}><ArrowRight size={17} /></button></td></tr>)}</tbody></table></div>
      {!filtered.length && <div className="empty"><FileSearch size={28} /><h3>{works.length ? '没有找到匹配作品' : '这个样本集还没有作品'}</h3><p>{works.length ? '换一个关键词，或清除文本范围筛选。' : '可以从标题与导语开始；没有的内容不会自动补齐。'}</p>{!works.length && <button className="btn" onClick={openImport}>了解如何导入</button>}</div>}
      <div className="table-footer"><span>显示 {filtered.length} / {works.length} 篇作品</span><span>演示与真实数据始终分开比较</span></div>
    </section>
    <div className="bottom-grid"><section className="card guide-card"><div className="section-heading"><h2><FlaskConical size={17} /> 试着复查一条判断</h2><span className="pill green">3 分钟演示</span></div><ol className="guide-steps"><li><span>01</span><div><b>打开作品剖面</b><p>看看“男方后悔”为什么不等于“双方复合”。</p></div></li><li><span>02</span><div><b>沿引用回到原文</b><p>核对版本、段落、精确位置，再判断语义。</p></div></li><li><span>03</span><div><b>查看 SQL 与研究轨迹</b><p>缺失指标就停止比较，保留下一步验证计划。</p></div></li></ol>{works[0] && <button className="text-button" onClick={() => openWork(works[0])}>从第一篇作品开始 <ArrowRight size={15} /></button>}</section><section className="card ledger-card"><div className="section-heading"><h2><Clock3 size={17} /> 任务记录</h2><span className="caption">真实运行 / 非模拟进度</span></div>{runs.length ? <div className="run-list">{runs.slice(-4).reverse().map(r => <button key={r.id} onClick={() => openRun(r)}><span className={`run-indicator ${r.status === 'completed' ? 'success' : ''}`} /><span><b>{r.mode === 'fixture' ? '预计算夹具校验' : '模型结构化抽取'}</b><small>{r.id} · {r.durationMs} ms</small></span><span className="pill neutral">{r.status}</span><ChevronRight size={14} /></button>)}</div> : <div className="ledger-empty"><ListChecks size={28} /><h3>{local ? '等待第一条任务记录' : '演示不伪造在线任务'}</h3><p>{local ? '在作品剖面回放夹具，或经授权后调用模型。' : '本地版保留调用、错误、重试及幂等记录。'}</p><span className="mini-code">inspect → extract → validate → review</span></div>}</section></div>
  </>
}

export function ProfilePanel({ work, works, local, busy, providerReady, onEvidence, onReview, onAnalyze, onSelect }: { work: Work; works: Work[]; local: boolean; busy: boolean; providerReady: boolean; onEvidence: (id: string) => void; onReview: (a: Annotation) => void; onAnalyze: (mode: 'fixture' | 'live') => void; onSelect: (id: string) => void }) {
  return <><section className="card work-hero"><div className="work-hero-top"><div className="book-tile big"><BookOpen size={28} /></div><div className="work-title"><div className="overline">{work.id} <span>/</span> {work.versionId} <span>/</span> {work.isSynthetic ? '原创虚构作品 · 演示夹具' : '本地私有作品'}</div><h2>{work.title}</h2><p>{work.author || '作者未填写'} · {scopeNames[work.scope]}</p></div><select className="work-picker" aria-label="切换作品" value={work.id} onChange={e => onSelect(e.target.value)}>{works.map(w => <option key={w.id} value={w.id}>{w.title}</option>)}</select></div><div className="work-hero-bottom"><span><ShieldCheck size={14} />{work.rightsStatus}</span><span>结尾范围：{work.endingConfirmed && work.scope === 'full_text' ? '已确认' : '未确认，不推断完整结局'}</span><div className="work-actions">{work.isSynthetic && <button className="btn small" disabled={!local || busy} onClick={() => onAnalyze('fixture')}><Play size={13} />回放夹具</button>}<button className="btn primary small" disabled={!local || busy || !providerReady || !work.modelConsent} title={!work.modelConsent ? '该作品未授权模型外发，请通过导入时的确认设置授权' : !providerReady ? '请在服务端配置模型' : '将已授权作品发送至配置的模型端点'} onClick={() => onAnalyze('live')}><Sparkles size={13} />模型抽取</button></div></div></section>
    <div className="profile-grid"><section className="card annotation-card"><div className="section-heading"><div><h2>内容判断 <span className="count">8 个维度</span></h2><p>分开识别关系结果与人物目标，不将女频等同于恋爱。</p></div><span className="pill neutral">{local ? '支持人工修订' : '只读快照'}</span></div><div className="annotation-list">{groups.map((group, i) => { const a = work.annotations.find(a => a.group === group); return <article className={`annotation-row ${!a || a.value === 'unknown' ? 'unknown-row' : ''}`} key={group}><span className="annotation-index">{String(i + 1).padStart(2, '0')}</span><div className="annotation-body"><div className="annotation-heading"><span>{group}</span><span className={`review-dot ${a?.reviewStatus === '已审核' ? 'reviewed' : ''}`}>{a?.reviewStatus ?? '待审核'}</span></div><h3>{valueNames[a?.value ?? 'unknown'] ?? a?.value}</h3><p>{a?.rationale || '当前文本或证据不足，保留 unknown，不自动填充。'}</p><div className="evidence-links">{a?.evidenceIds.map(id => <button key={id} onClick={() => onEvidence(id)}><Link2 size={12} />{id}</button>)}</div></div>{a && <button className="annotation-edit" onClick={() => onReview(a)} disabled={!local || busy} title={local ? '人工审核并保存版本' : '本地版可修改'}><GitBranch size={14} /><span>审核</span></button>}</article> })}</div></section>
      <aside className="profile-side"><section className="card promise-card"><div className="eyebrow">PROMISE → PAYOFF</div><h2>承诺是怎样走向结果的？</h2><div className="promise-timeline">{(['标题', '导语', '开篇', '结尾'] as const).map((field, i) => { const ev = work.evidence.find(e => e.field === field); const allowed = field !== '结尾' || work.scope === 'full_text' && work.endingConfirmed; return <div key={field} className={`promise-node ${ev && allowed ? '' : 'missing'}`}><span className="node-number">{i + 1}</span><div><h3>{field}<small>{['建立期待', '具体化承诺', '冲突是否发生', '结果是否对应'][i]}</small></h3>{ev && allowed ? <><p>“{ev.quote}”</p><button className="text-button" onClick={() => onEvidence(ev.id)}>核对原文 <ArrowRight size={12} /></button></> : <p className="muted">{field === '结尾' ? '未获确认的全文结尾，不输出兑现结论。' : '没有足够证据，等待导入或人工标注。'}</p>}</div></div> })}</div></section><section className="card boundary-card"><CircleHelp size={20} /><h3>保留“尚不知道”</h3><p>精确匹配只证明引用存在，不证明解释正确。审核时需要检查反例、叙事语境和文本范围。</p><dl><dt>正文段落</dt><dd>{work.paragraphs.length}</dd><dt>模型外发授权</dt><dd>{work.modelConsent ? '已授权' : '未授权'}</dd><dt>内容指纹</dt><dd className="mono hash" title={work.contentHash}>{work.contentHash?.slice(0, 16) || '待后端生成'}…</dd></dl></section></aside></div>
    <section className="card corpus-card"><div className="section-heading"><h2><BookOpen size={17} /> 当前版本文本</h2><span className="caption">段落内 Unicode code point 计数 · 左闭右开区间</span></div><details><summary>展开文本与段落编号 <ChevronRight size={15} /></summary><div className="corpus"><article><span>标题</span><p>{work.title}</p></article><article><span>导语</span><p>{work.intro || '未提供'}</p></article>{work.paragraphs.map(p => <article key={p.id}><span>{p.id}<small>{p.label}</small></span><p>{p.text}</p></article>)}</div></details></section>
  </>
}

export function ComparisonPanel({ works, comparison: c, revision, group, setGroup, reviewedOnly, setReviewedOnly, local, busy, onCompare, onEvidence, onWork }: { works: Work[]; comparison: Comparison | null; revision: number; group: string; setGroup: (g: string) => void; reviewedOnly: boolean; setReviewedOnly: (v: boolean) => void; local: boolean; busy: boolean; onCompare: () => void; onEvidence: (id: string) => void; onWork: (w: Work) => void }) {
  const stale = c && c.revision !== revision
  return <><section className="card analysis-controls"><label><span>比较维度</span><select value={group} onChange={e => setGroup(e.target.value)}>{groups.map(g => <option key={g}>{g}</option>)}</select></label><div className="cohort-label"><span>当前样本范围</span><b>{works.length} 篇 · {works.every(w => w.isSynthetic) ? '原创演示' : '本地私有'}</b></div><label className="checkbox-label"><input type="checkbox" checked={reviewedOnly} disabled={!local} onChange={e => setReviewedOnly(e.target.checked)} />仅纳入已审核标签</label><button className="btn primary" disabled={busy || !works.length} onClick={onCompare}><Database size={15} />{local ? '执行比较查询' : '查看该维度快照'}</button></section>
    {!c ? <div className="empty card large-empty"><Database size={32} /><h2>先定义范围，再执行比较</h2><p>每次比较保留实际 SQL、参数、数据修订和排除原因。</p><p className="muted">标签频次与指标比较分别计算；没有指标也可以做内容研究。</p></div> : <>
      {stale && <div className="banner warning"><GitBranch size={16} />当前结果基于 r{c.revision}，数据已更新为 r{revision}。请重新查询。</div>}
      <div className="analysis-summary"><span><b>{c.sampleCount}</b> 篇样本</span><span><b>{c.missingCount}</b> 篇无可用判断</span><span><b>{c.metricGroups.length}</b> 个可比指标组</span><span className="query-id">{c.queryId} · {c.durationMs} ms</span></div>
      <div className="comparison-grid"><section className="card frequency-card"><div className="section-heading"><div><h2>{c.group}分布</h2><p>描述当前样本，不推断平台偏好或内容效果。</p></div><span className="pill neutral">n = {c.sampleCount}</span></div>{c.frequencies.length ? <div className="frequency-list">{c.frequencies.map((f, i) => <div className="frequency-row" key={f.value}><div className="frequency-label"><span><i style={{ background: ['#21685d', '#548f7d', '#8fb5a4', '#b7cec1'][i % 4] }} />{valueNames[f.value] ?? f.value}</span><b>{f.count}<small> 篇</small></b></div><div className="bar-track"><span style={{ width: `${c.sampleCount ? f.count / c.sampleCount * 100 : 0}%`, background: ['#21685d', '#548f7d', '#8fb5a4', '#b7cec1'][i % 4] }} /></div><div className="frequency-sources">{f.workIds.map(id => { const work = works.find(w => w.id === id); return work && <button key={id} onClick={() => onWork(work)}>{work.title}<ChevronRight size={11} /></button> })}</div>{f.evidenceIds.length > 0 && <div className="evidence-links">{f.evidenceIds.map(id => <button key={id} onClick={() => onEvidence(id)}><Link2 size={11} />{id}</button>)}</div>}</div>)}</div> : <div className="empty"><CircleHelp size={26} /><h3>没有可纳入的非空判断</h3><p>先审核标签和原文证据；unknown 不参与已知标签频次。</p></div>}</section>
        <section className="card metric-card"><div className="section-heading"><div><h2>指标可比性</h2><p>定义 × 渠道 × 窗口 × 计数单位</p></div><ShieldCheck size={19} className="teal" /></div>{c.metricGroups.length ? c.metricGroups.map(m => <article className="metric-group" key={m.key}><div className="metric-definition"><span className="pill green">通过口径检查</span><b>{m.definition}</b></div><p>{m.channel} · {m.windowSpec} · {m.countingUnit}</p><div className="metric-values"><div><span>点击 / 曝光</span><strong>{formatPercent(m.ctr)}</strong><small>按分子分母加权，非 CTR 均值</small></div><div><b>{m.clicks.toLocaleString()}</b><span>点击</span><b>{m.impressions.toLocaleString()}</b><span>曝光</span></div></div><details><summary>{m.workIds.length} 篇作品 · 查看原始观测</summary><pre>{JSON.stringify(m.observations, null, 2)}</pre></details></article>) : <div className="empty"><Database size={28} /><h3>指标比较分支停止</h3><p>没有通过检查的曝光与点击，不生成 CTR，也不推断真实表现。</p></div>}<div className="subtle-note">演示指标是虚构数据。小样本中的共现不构成因果或选题结论。</div></section></div>
      <section className="card exclusions-card"><div className="section-heading"><h2>没有纳入比较的数据 <span className="count">{c.excluded.length}</span></h2><span className="caption">缺失不填零，不可比不合并</span></div>{c.excluded.length ? <div className="exclusion-list">{c.excluded.map((e, i) => <div key={`${e.workId}-${i}`}><span className="pill amber">已排除</span><b>{works.find(w => w.id === e.workId)?.title ?? e.workId}</b><span>{e.reason}</span></div>)}</div> : <p className="muted padded">没有额外排除项。通过检查仍不代表可以做因果解释。</p>}</section>
      <section className="card sql-card"><details><summary><span><Code2 size={17} />查看实际执行的 SQL 与参数</span><span className="caption">只读查询 · r{c.revision}</span></summary><div className="sql-content"><div className="query-meta"><span>数据快照 <code>{JSON.stringify(c.sourceSnapshot)}</code></span><span>耗时 {c.durationMs} ms</span></div><pre>{c.sql}</pre><h4>绑定参数</h4><pre>{JSON.stringify(c.params, null, 2)}</pre></div></details></section>
    </>}</>
}

export function MemoPanel({ report, stale, question, setQuestion, local, busy, group, onGenerate, onEvidence, onExport }: { report: Report | null; stale: boolean; question: string; setQuestion: (s: string) => void; local: boolean; busy: boolean; group: string; onGenerate: () => void; onEvidence: (id: string) => void; onExport: (f: 'md' | 'html' | 'xlsx') => void }) {
  return <><section className="card research-question"><div><span className="eyebrow">RESEARCH QUESTION</span><label htmlFor="research-question">这次研究想回答什么？</label><textarea id="research-question" value={question} onChange={e => setQuestion(e.target.value)} readOnly={!local} maxLength={1000} rows={2} /><p>当前比较维度：{group} · 有界规则控制器，不将自由问题伪装成开放式规划能力。</p></div><button className="btn primary" disabled={busy || !question.trim()} onClick={onGenerate}><Play size={15} />{local ? '运行研究工作流' : '打开预计算报告'}</button></section>
    {stale && <div className="banner warning"><GitBranch size={16} />标签或样本已有修订。这份备忘录已过期，重新生成后才能导出。</div>}
    {report?.refusal && <div className="banner warning"><CircleHelp size={16} />{report.refusal}</div>}
    {!report ? <div className="empty card large-empty"><FileSearch size={32} /><h2>让每条建议有据可依</h2><p>检查数据 → 选择样本 → 执行 SQL → 核对证据 → 比较口径 → 写出备忘录</p><p>缺少指标时，保留内容观察、限制和采集计划。</p></div> : <div className="memo-grid"><article className="card report-sheet"><div className="report-kicker"><span>HERLENS / RESEARCH NOTE</span><span>{report.id}</span></div><h2>从情绪承诺，到可验证的内容假设</h2><p className="report-question">{report.question}</p><div className="report-meta"><span>样本 n = {report.sampleCount}</span><span>数据修订 r{report.revision}</span><span>{report.createdAt?.slice(0, 10)}</span><span className={`pill ${stale ? 'amber' : 'green'}`}>{stale ? '已过期' : '当前版本'}</span></div><div className="report-disclaimer"><FlaskConical size={17} /><span>本报告是描述性研究。演示样本不能代表平台总体；没有可比指标时，不输出表现归因。</span></div>{report.findings.map((f, i) => <section className="finding" key={f.id}><div className="finding-title"><span>0{i + 1}</span><h3>{f.title}</h3></div><p className="finding-observation">{f.observation}</p><div className="evidence-links">{f.evidenceIds.map(id => <button onClick={() => onEvidence(id)} key={id}><Link2 size={12} />{id}</button>)}{f.queryIds.map(id => <span className="query-reference" key={id}><Database size={12} />{id}</span>)}</div><dl className="finding-details"><div><dt>适用范围</dt><dd>{f.scope}</dd></div><div><dt>还不能说明</dt><dd>{f.limitation}</dd></div><div className="next-step"><dt>下一步验证</dt><dd>{f.nextStep}<small>判断标准：{f.criterion}</small></dd></div></dl></section>)}<div className="report-end"><Check size={15} />判断有边界，验证有下一步。</div></article><aside className="memo-side"><section className="card trace-card"><div className="section-heading"><div><h2>研究工具轨迹</h2><p>真实函数调用，最多 6 步</p></div><span className="pill green">{report.trace.length} 步</span></div><div className="trace-mode"><i />deterministic-research<small>规则编排 · 非 LLM 自由规划</small></div><TracePanel steps={report.trace} /></section><section className="card export-card"><h3>带走这份研究</h3><p>保存判断、引用与局限，便于复查和下一次迭代。</p><button className="btn" disabled={stale || busy} onClick={() => onExport('md')}><ArrowDownToLine size={15} />Markdown 备忘录</button><button className="btn" disabled={stale || busy} onClick={() => onExport('html')}><ArrowDownToLine size={15} />可打印 HTML / PDF</button><button className="btn" disabled={stale || busy} onClick={() => onExport('xlsx')}><ArrowDownToLine size={15} />Excel · 四张可审计表</button><small>{local ? '导出前检查报告修订，过期报告不会被误用。' : '公开版导出经过隔离生成的原创演示报告。'}</small></section></aside></div>}
  </>
}
